version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: repcheck_web
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file:
      - .env
    environment:
      - REDIS_URL=${REDIS_URL}

  redis:
    image: redis:7-alpine
    container_name: repcheck_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
  db:
    image: postgres:13
    container_name: repcheck_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  postgres_data:
      driver: local
  redis_data:
      driver: local
