version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: repcheck_web
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env.dev
    environment:
      DJANGO_ENV: ${DJANGO_ENV}
  db:
    image: postgres:13
    container_name: repcheck_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env.dev

volumes:
  postgres_data:
      driver: local
