# Generated by Django 5.1.6 on 2025-08-14 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyCongressRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField(unique=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('pdf_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Daily Congressional Record',
                'verbose_name_plural': 'Daily Congressional Records',
            },
        ),
    ]
