# Generated by Django 5.1.6 on 2025-07-14 17:43

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('congress', '0009_member_fully_processed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('summary', models.CharField(max_length=1000)),
                ('bill_id', models.CharField(max_length=50)),
                ('introduced_date', models.DateField()),
                ('status', models.CharField(max_length=100)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=15), size=5)),
                ('congress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='congress.congress')),
            ],
        ),
    ]
