# Generated by Django 5.1.6 on 2025-07-14 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bills',
            name='url',
            field=models.URLField(default='', max_length=250),
        ),
    ]
