# Generated by Django 5.1.6 on 2025-07-14 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0002_bills_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bills',
            name='bill_id',
        ),
        migrations.RemoveField(
            model_name='bills',
            name='congress',
        ),
        migrations.RemoveField(
            model_name='bills',
            name='introduced_date',
        ),
        migrations.RemoveField(
            model_name='bills',
            name='status',
        ),
        migrations.RemoveField(
            model_name='bills',
            name='title',
        ),
        migrations.RemoveField(
            model_name='bills',
            name='url',
        ),
    ]
