# Generated by Django 5.1.6 on 2025-07-15 03:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0003_remove_bills_bill_id_remove_bills_congress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bills',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=25), size=3),
        ),
    ]
