# Generated by Django 5.1.6 on 2025-07-17 16:21

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('congress', '0010_alter_congress_options'),
        ('legislation', '0004_alter_bills_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bills',
            name='summary',
        ),
        migrations.AddField(
            model_name='bills',
            name='congress',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='congress.congress'),
        ),
        migrations.AddField(
            model_name='bills',
            name='full_text_url',
            field=models.URLField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='bills',
            name='gemini_summary',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='bills',
            name='latest_action',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bills',
            name='latest_action_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='bills',
            name='origin_chamber',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='bills',
            name='title',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='bills',
            name='type',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='bills',
            name='url',
            field=models.URLField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='bills',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bills',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=25), null=True, size=3),
        ),
    ]
