# Generated by Django 5.1.6 on 2025-07-18 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0005_remove_bills_summary_bills_congress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bills',
            name='gemini_summary',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='bills',
            name='type',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
