# Generated by Django 5.1.6 on 2025-07-18 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0006_alter_bills_gemini_summary_alter_bills_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='bills',
            name='bill_number',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
