# Generated by Django 5.1.6 on 2025-09-16 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0007_bills_bill_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bills',
            old_name='bill_number',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='bills',
            old_name='origin_chamber',
            new_name='originChamber',
        ),
    ]
