# Generated by Django 5.1.6 on 2025-07-10 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizens', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizen',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
    ]
