# Generated by Django 5.1.6 on 2025-04-17 22:53

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Congress',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('congress_number', models.IntegerField(unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Congresses',
                'ordering': ['-congress_number'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bioguide_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=50)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('image_attribution', models.TextField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MemberDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('website_url', models.URLField(null=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('open_secrets_id', models.CharField(blank=True, max_length=50, null=True)),
                ('twitter_handle', models.CharField(blank=True, max_length=50, null=True)),
                ('facebook_handle', models.CharField(blank=True, max_length=50, null=True)),
                ('youtube_id', models.CharField(blank=True, max_length=50, null=True)),
                ('instagram_handle', models.CharField(blank=True, max_length=50, null=True)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='congress.member')),
            ],
            options={
                'verbose_name_plural': 'Member Details',
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('chamber', models.CharField(choices=[('Senate', 'Senate'), ('House', 'House')], max_length=10)),
                ('party', models.CharField(max_length=50)),
                ('district', models.IntegerField(blank=True, null=True)),
                ('start_year', models.IntegerField()),
                ('end_year', models.IntegerField(blank=True, null=True)),
                ('congress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='congress.congress')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='congress.member')),
            ],
            options={
                'unique_together': {('member', 'congress')},
            },
        ),
    ]
