# Generated by Django 5.1.6 on 2025-02-12 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('congress', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='congress',
            name='last_updated',
        ),
    ]
