# Generated by Django 5.1.6 on 2025-04-18 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('congress', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='chamber',
            field=models.CharField(choices=[('Senate', 'Senate'), ('House', 'House')], max_length=20),
        ),
    ]
