# Generated by Django 5.1.6 on 2025-04-22 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('congress', '0002_alter_membership_chamber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='chamber',
            field=models.CharField(choices=[('Senate', 'Senate'), ('House', 'House')], max_length=25),
        ),
    ]
