# Generated by Django 5.1.6 on 2025-04-24 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('congress', '0003_alter_membership_chamber'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberdetails',
            name='contact_form',
            field=models.URLField(blank=True, null=True),
        ),
    ]
