# Generated by Django 5.1.6 on 2025-04-24 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('congress', '0004_memberdetails_contact_form'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberdetails',
            name='contact_form',
        ),
    ]
