# Generated by Django 5.1.6 on 2025-04-24 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('congress', '0005_remove_memberdetails_contact_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberdetails',
            name='wikipedia',
            field=models.URLField(blank=True, null=True),
        ),
    ]
