# Generated by Django 5.1.6 on 2025-05-12 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('congress', '0006_memberdetails_wikipedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='chamber',
            field=models.CharField(max_length=25),
        ),
    ]
