# Generated by Django 5.1.6 on 2025-05-17 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('congress', '0007_alter_membership_chamber'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='cosponsored_legislation_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='membership',
            name='leadership_role',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='sponsored_legislation_count',
            field=models.IntegerField(default=0),
        ),
    ]
