# Generated by Django 5.1.6 on 2025-06-04 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('congress', '0008_membership_cosponsored_legislation_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='fully_processed',
            field=models.BooleanField(default=False),
        ),
    ]
