# Generated by Django 5.1.6 on 2025-07-17 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('congress', '0009_member_fully_processed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='congress',
            options={'ordering': ['congress_number'], 'verbose_name_plural': 'Congresses'},
        ),
    ]
