# Generated by Django 5.1.6 on 2025-07-25 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('congress', '0010_alter_congress_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='congress',
            options={'ordering': ['-congress_number'], 'verbose_name_plural': 'Congresses'},
        ),
    ]
