# Generated by Django 5.1.6 on 2025-09-02 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('congress', '0011_alter_congress_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='state',
            field=models.CharField(default='', max_length=50),
        ),
    ]
