# Generated by Django 5.1.6 on 2025-09-22 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('congress', '0010_auto_20250803_1332'),
        ('congress', '0012_membership_state'),
    ]

    operations = [
    ]
