name: Deploy to Production

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Install Cloudflared
        run: |
          sudo apt-get update
          sudo apt-get install -y cloudflared

      - name: Set up SSH with Cloudflare Tunnel
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "Host ${{ secrets.VM_HOST }}" >> ~/.ssh/config
          echo "  ProxyCommand cloudflared access ssh --hostname ${{ secrets.VM_HOST }}" >> ~/.ssh/config

      - name: Stop and remove existing containers
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.VM_HOST }} << 'EOF'
            docker-compose down
          EOF

      - name: Pull latest changes
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.VM_HOST }} << 'EOF'
            cd /home/${{ secrets.SSH_USERNAME }}/repcheck/
            git pull origin production
          EOF

      - name: Rebuild and start the containers
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.VM_HOST }} << 'EOF'
            cd /home/${{ secrets.SSH_USERNAME }}/repcheck/
            docker-compose up --build -d
          EOF
